
  global:
    scrape_interval: 60s # By default, scrape targets every 15 seconds.
    scrape_timeout: 180s # Per-target timeout when scraping this job.
    evaluation_interval: 60s # By default, scrape targets every 15 seconds.

  # Load and evaluate rules in this file every 'evaluation_interval' seconds.
  #rule_files:
    # - "first.rules"
    # - "second.rules"

  scrape_configs:
    - job_name: 'dev'
      file_sd_configs:
        - names:
            - '/opt/jmx_exporter/conf/sd/*.yml'
          refresh_interval: 60s

    - job_name: prometheus
      honor_labels: true
      target_groups:
      - targets: ['localhost:9090']
